name: Deploy Stargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"

    env:
      working-directory: /etc/stargate

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: systemctl restart stargate
