name: Deploy Stargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: "self-hosted"

    env:
      working-directory: /var/lib/stargate

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restart service
        run: systemctl restart stargate

      - name: Check web UI
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://127.0.0.1:4080/admin
          follow-redirect: true
          max-attempts: 10
          retry-delay: 30s
